# Generated by Django 4.1.5 on 2023-01-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onama',
            options={'ordering': ('-publish',), 'verbose_name_plural': 'Onama'},
        ),
    ]
