# Generated by Django 4.1.5 on 2023-01-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_alter_onama_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onama',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
