# Generated by Django 4.1.5 on 2023-04-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_braintree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='m_broj',
            field=models.CharField(default=True, max_length=8),
        ),
        migrations.AddField(
            model_name='order',
            name='pib',
            field=models.CharField(default=True, max_length=9),
        ),
    ]
