# Generated by Django 4.1.5 on 2023-04-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_company_order_m_broj_order_pib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='m_broj',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='pib',
            field=models.CharField(max_length=9),
        ),
    ]
