# Generated by Django 4.1.5 on 2023-05-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_osnovica_orderitem_pdv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='pdv',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=10),
        ),
    ]
