# Generated by Django 4.1.5 on 2023-05-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderitem_osnovica_alter_orderitem_pdv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='p',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=10),
        ),
    ]
