# Generated by Django 4.1.5 on 2023-05-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='p',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=10),
        ),
    ]
